--- 
abstract: Automatically Linkfy
author: 
  - "Copyright (c) 2006-2007 Daisuke Maki <daisuke@endeworks.jp<gt>. "
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Text-AutoLink
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::TreeBuilder: 0
  Module::Pluggable: 0
  URI: 0
  perl: 5.6.0
version: 0.03000
